export enum AuthenticationCodes {
  ClaimsTooLarge = 'auth/claims-too-large',
  EmailAlreadyExists = 'auth/email-already-exists',
  IdTokenExpired = 'auth/id-token-expired',
  IdTokenRevoked = 'auth/id-token-revoked',
  InsufficientPermission = 'auth/insufficient-permission',
  InternalError = 'auth/internal-error',
  InvalidArgument = 'auth/invalid-argument',
  InvalidClaims = 'auth/invalid-claims',
  InvalidContinueUri = 'auth/invalid-continue-uri',
  InvalidCreationTime = 'auth/invalid-creation-time',
  InvalidCredential = 'auth/invalid-credential',
  InvalidDisabledField = 'auth/invalid-disabled-field',
  InvalidDisplayName = 'auth/invalid-display-name',
  InvalidDynamicLinkDomain = 'auth/invalid-dynamic-link-domain',
  InvalidEmail = 'auth/invalid-email',
  InvalidEmailVerified = 'auth/invalid-email-verified',
  InvalidHashAlgorithm = 'auth/invalid-hash-algorithm',
  InvalidHashBlockSize = 'auth/invalid-hash-block-size',
  InvalidHashDerivedKeyLength = 'auth/invalid-hash-derived-key-length',
  InvalidHashKey = 'auth/invalid-hash-key',
  InvalidHashMemoryCost = 'auth/invalid-hash-memory-cost',
  InvalidHashParallelization = 'auth/invalid-hash-parallelization',
  InvalidHashRounds = 'auth/invalid-hash-rounds',
  InvalidHashSaltSeparator = 'auth/invalid-hash-salt-separator',
  InvalidIdToken = 'auth/invalid-id-token',
  InvalidLastSignInTime = 'auth/invalid-last-sign-in-time',
  InvalidPageToken = 'auth/invalid-page-token',
  InvalidPassword = 'auth/auth/invalid-password',
  InvalidPasswordHash = 'auth/invalid-password-hash',
  InvalidPasswordSalt = 'auth/invalid-password-salt',
  InvalidPhoneNumber = 'auth/invalid-phone-number',
  InvalidPhotoUrl = 'auth/invalid-photo-url',
  InvalidProviderData = 'auth/invalid-provider-data',
  InvalidProviderId = 'auth/invalid-provider-id',
  InvalidOauthResponseType = 'auth/invalid-oauth-responsetype',
  InvalidSessionCookieDuration = 'auth/invalid-hash-salt-separator',
  InvalidUid = 'auth/invalid-uid',
  InvalidUserImport = 'auth/invalid-user-import',
  MaximumUserCountExceeded = 'auth/maximum-user-count-exceeded',
  MissingAndroidPkgName = 'auth/missing-android-pkg-name',
  MissingContinueUri = 'auth/missing-continue-uri',
  MissingHashAlgorithm = 'auth/missing-hash-algorithm',
  MissingIosBundleId = 'auth/missing-ios-bundle-id',
  MissingUid = 'auth/missing-uid',
  MissingOauthClientSecret = 'auth/missing-oauth-client-secret',
  OperationNotAllowed = 'auth/operation-not-allowed',
  PhoneNumberAlreadyExists = 'auth/phone-number-already-exists',
  ProjectNotFound = 'auth/project-not-found',
  ReservedClaims = 'auth/reserved-claims',
  SessionCookieExpired = 'auth/session-cookie-expired',
  SessionCookieRevoked = 'auth/session-cookie-revoked',
  UidAlreadyExists = 'auth/uid-already-exists',
  UnauthorizedContinueUri = 'auth/unauthorized-continue-uri',
  UserNotFound = 'auth/user-not-found',
  WrongPassword = 'auth/wrong-password',
}

export const AuthenticationCodeDisplay: Record<AuthenticationCodes, string> = {
  [AuthenticationCodes.ClaimsTooLarge]: 'auth/claims-too-large',
  [AuthenticationCodes.EmailAlreadyExists]: 'auth/email-already-exists',
  [AuthenticationCodes.IdTokenExpired]: 'auth/id-token-expired',
  [AuthenticationCodes.IdTokenRevoked]: 'auth/id-token-revoked',
  [AuthenticationCodes.InsufficientPermission]: 'auth/insufficient-permission',
  [AuthenticationCodes.InternalError]: 'auth/internal-error',
  [AuthenticationCodes.InvalidArgument]: 'auth/invalid-argument',
  [AuthenticationCodes.InvalidClaims]: 'auth/invalid-claims',
  [AuthenticationCodes.InvalidContinueUri]: 'auth/invalid-continue-uri',
  [AuthenticationCodes.InvalidCreationTime]: 'auth/invalid-creation-time',
  [AuthenticationCodes.InvalidCredential]: 'auth/invalid-credential',
  [AuthenticationCodes.InvalidDisabledField]: 'auth/invalid-disabled-field',
  [AuthenticationCodes.InvalidDisplayName]: 'auth/invalid-display-name',
  [AuthenticationCodes.InvalidDynamicLinkDomain]:
    'auth/invalid-dynamic-link-domain',
  [AuthenticationCodes.InvalidEmail]: 'auth/invalid-email',
  [AuthenticationCodes.InvalidEmailVerified]: 'auth/invalid-email-verified',
  [AuthenticationCodes.InvalidHashAlgorithm]: 'auth/invalid-hash-algorithm',
  [AuthenticationCodes.InvalidHashBlockSize]: 'auth/invalid-hash-block-size',
  [AuthenticationCodes.InvalidHashDerivedKeyLength]:
    'auth/invalid-hash-derived-key-length',
  [AuthenticationCodes.InvalidHashKey]: 'auth/invalid-hash-key',
  [AuthenticationCodes.InvalidHashMemoryCost]: 'auth/invalid-hash-memory-cost',
  [AuthenticationCodes.InvalidHashParallelization]:
    'auth/invalid-hash-parallelization',
  [AuthenticationCodes.InvalidHashRounds]: 'auth/invalid-hash-rounds',
  [AuthenticationCodes.InvalidHashSaltSeparator]:
    'auth/invalid-hash-salt-separator',
  [AuthenticationCodes.InvalidIdToken]: 'auth/invalid-id-token',
  [AuthenticationCodes.InvalidLastSignInTime]: 'auth/invalid-last-sign-in-time',
  [AuthenticationCodes.InvalidPageToken]: 'auth/invalid-page-token',
  [AuthenticationCodes.InvalidPassword]: 'auth/auth/invalid-password',
  [AuthenticationCodes.InvalidPasswordHash]: 'auth/invalid-password-hash',
  [AuthenticationCodes.InvalidPasswordSalt]: 'auth/invalid-password-salt',
  [AuthenticationCodes.InvalidPhoneNumber]: 'auth/invalid-phone-number',
  [AuthenticationCodes.InvalidPhotoUrl]: 'auth/invalid-photo-url',
  [AuthenticationCodes.InvalidProviderData]: 'auth/invalid-provider-data',
  [AuthenticationCodes.InvalidProviderId]: 'auth/invalid-provider-id',
  [AuthenticationCodes.InvalidOauthResponseType]:
    'auth/invalid-oauth-responsetype',
  [AuthenticationCodes.InvalidSessionCookieDuration]:
    'auth/invalid-hash-salt-separator',
  [AuthenticationCodes.InvalidUid]: 'auth/invalid-uid',
  [AuthenticationCodes.InvalidUserImport]: 'auth/invalid-user-import',
  [AuthenticationCodes.MaximumUserCountExceeded]:
    'auth/maximum-user-count-exceeded',
  [AuthenticationCodes.MissingAndroidPkgName]: 'auth/missing-android-pkg-name',
  [AuthenticationCodes.MissingContinueUri]: 'auth/missing-continue-uri',
  [AuthenticationCodes.MissingHashAlgorithm]: 'auth/missing-hash-algorithm',
  [AuthenticationCodes.MissingIosBundleId]: 'auth/missing-ios-bundle-id',
  [AuthenticationCodes.MissingUid]: 'auth/missing-uid',
  [AuthenticationCodes.MissingOauthClientSecret]:
    'auth/missing-oauth-client-secret',
  [AuthenticationCodes.OperationNotAllowed]: 'auth/operation-not-allowed',
  [AuthenticationCodes.PhoneNumberAlreadyExists]:
    'auth/phone-number-already-exists',
  [AuthenticationCodes.ProjectNotFound]: 'auth/project-not-found',
  [AuthenticationCodes.ReservedClaims]: 'auth/reserved-claims',
  [AuthenticationCodes.SessionCookieExpired]: 'auth/session-cookie-expired',
  [AuthenticationCodes.SessionCookieRevoked]: 'auth/session-cookie-revoked',
  [AuthenticationCodes.UidAlreadyExists]: 'auth/uid-already-exists',
  [AuthenticationCodes.UnauthorizedContinueUri]:
    'auth/unauthorized-continue-uri',
  [AuthenticationCodes.UserNotFound]: 'auth/user-not-found',
  [AuthenticationCodes.WrongPassword]: 'auth/wrong-password',
};
